/*
 * This file was automatically generated by EvoSuite
 */

package com.lts.swing.contentpanel;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.lts.swing.contentpanel.ContentPanelListenerHelper;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class ContentPanelListenerHelperEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      ContentPanelListenerHelper contentPanelListenerHelper0 = new ContentPanelListenerHelper();
      contentPanelListenerHelper0.addListener((Object) null);
      // Undeclared exception!
      try {
        contentPanelListenerHelper0.clearResumeAndFire(0, (Object) null);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test1()  throws Throwable  {
      ContentPanelListenerHelper contentPanelListenerHelper0 = new ContentPanelListenerHelper();
      contentPanelListenerHelper0.notifyListener((Object) null, (-838), (Object) null);
  }

  @Test
  public void test2()  throws Throwable  {
      ContentPanelListenerHelper contentPanelListenerHelper0 = new ContentPanelListenerHelper();
      // Undeclared exception!
      try {
        contentPanelListenerHelper0.notifyListener((Object) null, 1, (Object) null);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test3()  throws Throwable  {
      ContentPanelListenerHelper contentPanelListenerHelper0 = new ContentPanelListenerHelper();
      // Undeclared exception!
      try {
        contentPanelListenerHelper0.notifyListener((Object) null, 4, (Object) null);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }
}
