/*
 * This file was automatically generated by EvoSuite
 */

package com.lts.swing.table.rowmodel.transfer;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.lts.swing.table.rowmodel.transfer.TableTransferData;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TableTransferDataEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      int[] intArray0 = new int[3];
      DefaultTableModel defaultTableModel0 = new DefaultTableModel((Vector) null, 317);
      TableTransferData tableTransferData0 = new TableTransferData(intArray0, (TableModel) defaultTableModel0);
      assertNotNull(tableTransferData0);
  }
}
