/*
 * This file was automatically generated by EvoSuite
 */

package de.outstare.fortbattleplayer.player.actions;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import de.outstare.fortbattleplayer.model.Combatant;
import de.outstare.fortbattleplayer.player.actions.OnlineAction;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class CombatantActionEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      OnlineAction onlineAction0 = new OnlineAction((Combatant) null, true);
      Combatant combatant0 = onlineAction0.getActor();
      assertNull(combatant0);
  }
}
