/*
 * This file was automatically generated by EvoSuite
 */

package de.outstare.fortbattleplayer.player.actions;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import de.outstare.fortbattleplayer.model.Area;
import de.outstare.fortbattleplayer.model.CharacterClass;
import de.outstare.fortbattleplayer.model.Combatant;
import de.outstare.fortbattleplayer.model.Sector;
import de.outstare.fortbattleplayer.model.impl.SimpleArea;
import de.outstare.fortbattleplayer.model.impl.SimpleSector;
import de.outstare.fortbattleplayer.player.actions.TargetAction;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TargetActionEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      CharacterClass characterClass0 = CharacterClass.DUELANT;
      SimpleSector simpleSector0 = new SimpleSector((-1669), true, true, (-1669), 1118719, true, 16716049, characterClass0);
      SimpleArea simpleArea0 = new SimpleArea((-1669), 16716049, (Sector) simpleSector0);
      TargetAction targetAction0 = new TargetAction((Combatant) null, (Area) simpleArea0);
      // Undeclared exception!
      try {
        targetAction0.execute();
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test1()  throws Throwable  {
      CharacterClass characterClass0 = CharacterClass.DUELANT;
      SimpleSector simpleSector0 = new SimpleSector((-1669), true, true, (-1669), 1118719, true, 16716049, characterClass0);
      SimpleArea simpleArea0 = new SimpleArea((-1669), 16716049, (Sector) simpleSector0);
      TargetAction targetAction0 = new TargetAction((Combatant) null, (Area) simpleArea0);
      String string0 = targetAction0.toString();
      assertEquals("null moves to Area -1669/16716049 [occupied by null]", string0);
      assertNotNull(string0);
  }
}
