/*
 * This file was automatically generated by EvoSuite
 */

package com.lts.xmlser.fixups;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.lts.xmlser.fixups.ReferenceFixup;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class ReferenceFixupEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      ReferenceFixup referenceFixup0 = new ReferenceFixup();
      ReferenceFixup referenceFixup1 = new ReferenceFixup(referenceFixup0);
      assertFalse(referenceFixup1.equals(referenceFixup0));
  }

  @Test
  public void test1()  throws Throwable  {
      ReferenceFixup referenceFixup0 = new ReferenceFixup((Object) "value", (Integer) null);
      assertNotNull(referenceFixup0);
  }
}
