/*
 * This file was automatically generated by EvoSuite
 */

package com.lts.swing.filefield;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.lts.LTSException;
import com.lts.swing.LTSPanel;
import com.lts.swing.filefield.FileField;
import com.lts.swing.filefield.FileFieldPanel;
import java.awt.HeadlessException;
import java.awt.Window;
import javax.swing.JLabel;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class FileFieldPanelEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      FileFieldPanel fileFieldPanel0 = new FileFieldPanel();
      LTSPanel lTSPanel0 = (LTSPanel)fileFieldPanel0.createTopPanel();
      assertNotNull(lTSPanel0);
      assertEquals(1, lTSPanel0.getComponentCount());
  }

  @Test
  public void test1()  throws Throwable  {
      FileFieldPanel fileFieldPanel0 = new FileFieldPanel();
      String string0 = fileFieldPanel0.getHeading();
      assertNull(string0);
  }

  @Test
  public void test2()  throws Throwable  {
      FileFieldPanel fileFieldPanel0 = new FileFieldPanel();
      // Undeclared exception!
      try {
        fileFieldPanel0.initializeWindow((Window) null);
        fail("Expecting exception: HeadlessException");
      } catch(HeadlessException e) {
      }
  }

  @Test
  public void test3()  throws Throwable  {
      FileFieldPanel fileFieldPanel0 = new FileFieldPanel();
      JLabel jLabel0 = fileFieldPanel0.getHeadingLabel();
      assertNull(jLabel0);
  }

  @Test
  public void test4()  throws Throwable  {
      FileFieldPanel fileFieldPanel0 = new FileFieldPanel();
      fileFieldPanel0.createBottomPanel();
      assertEquals(2, fileFieldPanel0.getBottomPanelMode());
  }

  @Test
  public void test5()  throws Throwable  {
      FileFieldPanel fileFieldPanel0 = new FileFieldPanel();
      FileField fileField0 = fileFieldPanel0.getFileField();
      assertNull(fileField0);
  }

  @Test
  public void test6()  throws Throwable  {
      FileFieldPanel fileFieldPanel0 = new FileFieldPanel();
      JLabel jLabel0 = fileFieldPanel0.getFieldLabel();
      assertNull(jLabel0);
  }

  @Test
  public void test7()  throws Throwable  {
      FileFieldPanel fileFieldPanel0 = new FileFieldPanel();
      fileFieldPanel0.okButtonPressed();
      assertEquals(true, fileFieldPanel0.isDoubleBuffered());
  }

  @Test
  public void test8()  throws Throwable  {
      FileFieldPanel fileFieldPanel0 = new FileFieldPanel();
      LTSPanel lTSPanel0 = (LTSPanel)fileFieldPanel0.createCenterPanel();
      assertNotNull(lTSPanel0);
      assertEquals(2, lTSPanel0.getComponentCount());
  }

  @Test
  public void test9()  throws Throwable  {
      FileFieldPanel fileFieldPanel0 = new FileFieldPanel();
      fileFieldPanel0.setHeading("#");
      assertEquals("#", fileFieldPanel0.getHeading());
  }
}
