/*
 * This file was automatically generated by EvoSuite
 */

package com.lts.util;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.lts.util.VectorUtils;
import java.util.Vector;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class VectorUtilsEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      VectorUtils vectorUtils0 = new VectorUtils();
      assertNotNull(vectorUtils0);
  }

  @Test
  public void test1()  throws Throwable  {
      Object[] objectArray0 = new Object[5];
      Vector<Object> vector0 = VectorUtils.arrayToVector(objectArray0);
      assertNotNull(vector0);
      
      Object[] objectArray1 = VectorUtils.vectorToArray(vector0);
      assertEquals(5, vector0.size());
      assertNotNull(objectArray1);
      assertEquals("[null, null, null, null, null]", vector0.toString());
  }
}
