/*
 * This file was automatically generated by EvoSuite
 */

package com.lts.application.exception;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.lts.LTSException;
import com.lts.application.exception.ExceptionDetailsPanel;
import javax.swing.JDialog;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class ExceptionDetailsPanelEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      ExceptionDetailsPanel exceptionDetailsPanel0 = null;
      try {
        exceptionDetailsPanel0 = new ExceptionDetailsPanel((JDialog) null, "Grab from creen", "Grab from creen", "Grab from creen");
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }
}
