/*
 * This file was automatically generated by EvoSuite
 */

package com.lts.exception;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.lts.exception.DefaultExceptionHandler;
import com.lts.exception.ExceptionHandler;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class DefaultExceptionHandlerEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      DefaultExceptionHandler defaultExceptionHandler0 = new DefaultExceptionHandler();
      assertNotNull(defaultExceptionHandler0);
  }

  @Test
  public void test1()  throws Throwable  {
      // Undeclared exception!
      try {
        ExceptionHandler.processException((Exception) null);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }
}
