/*
 * This file was automatically generated by EvoSuite
 */

package com.lts.swing.table.dragndrop.test;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.lts.swing.table.dragndrop.test.CallgraphTranscriber;
import com.lts.swing.table.dragndrop.test.EventLog;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class CallgraphTranscriberEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      CallgraphTranscriber callgraphTranscriber0 = new CallgraphTranscriber();
      assertNotNull(callgraphTranscriber0);
  }

  @Test
  public void test1()  throws Throwable  {
      String string0 = EventLog.transcript();
      assertEquals("", string0);
  }
}
