/*
 * This file was automatically generated by EvoSuite
 */

package com.lts.swing.table.dragndrop.test;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.lts.swing.table.dragndrop.test.ImportDataCalled;
import java.awt.Component;
import java.awt.datatransfer.StringSelection;
import java.awt.datatransfer.Transferable;
import javax.swing.JToolBar;
import javax.swing.TransferHandler;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class ImportDataCalledEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      JToolBar jToolBar0 = new JToolBar();
      StringSelection stringSelection0 = new StringSelection("Z");
      TransferHandler.TransferSupport transferHandler_TransferSupport0 = new TransferHandler.TransferSupport((Component) jToolBar0, (Transferable) stringSelection0);
      ImportDataCalled importDataCalled0 = new ImportDataCalled(transferHandler_TransferSupport0);
      StringBuffer stringBuffer0 = new StringBuffer();
      importDataCalled0.appendSubclassToString(stringBuffer0);
      assertEquals("not a drop", stringBuffer0.toString());
      assertEquals(10, stringBuffer0.length());
  }
}
