/*
 * This file was automatically generated by EvoSuite
 */

package com.lts.swing.table.dragndrop.test;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.lts.swing.table.dragndrop.test.CallGraphLog;
import com.lts.swing.table.dragndrop.test.EventLog;
import com.lts.swing.table.dragndrop.test.LogTranscriber;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class LogTranscriberEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      LogTranscriber logTranscriber0 = new LogTranscriber();
      CallGraphLog callGraphLog0 = (CallGraphLog)EventLog.getInstance();
      String string0 = logTranscriber0.transcribe((EventLog) callGraphLog0);
      assertEquals("", string0);
  }
}
