/*
 * This file was automatically generated by EvoSuite
 */

package com.lts.swing.table.dragndrop.test;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.lts.swing.table.dragndrop.test.ProxyTransferHandler;
import java.awt.Component;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.StringSelection;
import java.awt.datatransfer.Transferable;
import java.awt.event.InputEvent;
import java.awt.event.MouseWheelEvent;
import javax.swing.Box;
import javax.swing.Icon;
import javax.swing.JComponent;
import javax.swing.JTextField;
import javax.swing.TransferHandler;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class ProxyTransferHandlerEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      ProxyTransferHandler proxyTransferHandler0 = new ProxyTransferHandler();
      Icon icon0 = proxyTransferHandler0.getVisualRepresentation((Transferable) null);
      assertNull(icon0);
  }

  @Test
  public void test1()  throws Throwable  {
      ProxyTransferHandler proxyTransferHandler0 = new ProxyTransferHandler();
      JTextField jTextField0 = new JTextField("s;BS4=}N]RAa yG;S", 0);
      StringSelection stringSelection0 = new StringSelection("s;BS4=}N]RAa yG;S");
      TransferHandler.TransferSupport transferHandler_TransferSupport0 = new TransferHandler.TransferSupport((Component) jTextField0, (Transferable) stringSelection0);
      boolean boolean0 = proxyTransferHandler0.canImport(transferHandler_TransferSupport0);
      assertEquals(false, boolean0);
  }

  @Test
  public void test2()  throws Throwable  {
      ProxyTransferHandler proxyTransferHandler0 = new ProxyTransferHandler();
      JTextField jTextField0 = new JTextField("s;BS4=}N]RAa yG;S", 0);
      StringSelection stringSelection0 = new StringSelection("s;BS4=}N]RAa yG;S");
      TransferHandler.TransferSupport transferHandler_TransferSupport0 = new TransferHandler.TransferSupport((Component) jTextField0, (Transferable) stringSelection0);
      boolean boolean0 = proxyTransferHandler0.importData(transferHandler_TransferSupport0);
      assertEquals(false, boolean0);
  }

  @Test
  public void test3()  throws Throwable  {
      ProxyTransferHandler proxyTransferHandler0 = new ProxyTransferHandler();
      String string0 = proxyTransferHandler0.toString();
      assertNotNull(string0);
  }

  @Test
  public void test4()  throws Throwable  {
      ProxyTransferHandler proxyTransferHandler0 = new ProxyTransferHandler();
      boolean boolean0 = proxyTransferHandler0.equals((Object) proxyTransferHandler0);
      assertEquals(true, boolean0);
  }

  @Test
  public void test5()  throws Throwable  {
      ProxyTransferHandler proxyTransferHandler0 = new ProxyTransferHandler();
      Box box0 = Box.createVerticalBox();
      MouseWheelEvent mouseWheelEvent0 = new MouseWheelEvent((Component) box0, (-1), (long) (-1), (-1), (-1), (-1), (-1), true, (-1), (-1), (-1));
      proxyTransferHandler0.exportAsDrag((JComponent) null, (InputEvent) mouseWheelEvent0, (-1));
      assertEquals(-1, mouseWheelEvent0.getScrollAmount());
  }

  @Test
  public void test6()  throws Throwable  {
      ProxyTransferHandler proxyTransferHandler0 = new ProxyTransferHandler();
      Clipboard clipboard0 = new Clipboard("SIcUg[");
      proxyTransferHandler0.exportToClipboard((JComponent) null, clipboard0, 887);
      assertEquals("SIcUg[", clipboard0.getName());
  }

  @Test
  public void test7()  throws Throwable  {
      ProxyTransferHandler proxyTransferHandler0 = new ProxyTransferHandler();
      Transferable transferable0 = proxyTransferHandler0.createTransferable((JComponent) null);
      assertNull(transferable0);
  }
}
