/*
 * This file was automatically generated by EvoSuite
 */

package com.lts.pest.data.event;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.lts.pest.data.event.ElementListenerHelper;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class ElementListenerHelperEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      ElementListenerHelper elementListenerHelper0 = new ElementListenerHelper();
      Object object0 = new Object();
      elementListenerHelper0.fireElementAdded(object0);
  }

  @Test
  public void test1()  throws Throwable  {
      ElementListenerHelper elementListenerHelper0 = new ElementListenerHelper();
      elementListenerHelper0.addListener((Object) "[]");
      // Undeclared exception!
      try {
        elementListenerHelper0.fireDeserialized();
        fail("Expecting exception: ClassCastException");
      } catch(ClassCastException e) {
        /*
         * java.lang.String cannot be cast to com.lts.pest.data.event.ElementHolderListener
         */
      }
  }

  @Test
  public void test2()  throws Throwable  {
      ElementListenerHelper elementListenerHelper0 = new ElementListenerHelper();
      elementListenerHelper0.fireAllChanged();
  }

  @Test
  public void test3()  throws Throwable  {
      ElementListenerHelper elementListenerHelper0 = new ElementListenerHelper();
      elementListenerHelper0.fireElementRemoved((Object) "[]");
  }

  @Test
  public void test4()  throws Throwable  {
      ElementListenerHelper elementListenerHelper0 = new ElementListenerHelper();
      elementListenerHelper0.fireElementChanged((Object) null, (Object) null);
  }
}
