/*
 * This file was automatically generated by EvoSuite
 */

package com.lts.xmlser;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.lts.xmlser.PostFixup;
import com.lts.xmlser.XmlSerializer;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class PostFixupEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      PostFixup postFixup0 = new PostFixup();
      XmlSerializer xmlSerializer0 = new XmlSerializer();
      postFixup0.performFixup(xmlSerializer0);
  }
}
