/*
 * This file was automatically generated by EvoSuite
 */

package com.lts.application.prop;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.lts.application.ApplicationException;
import com.lts.application.prop.DefaultCommandLinePolicy;
import java.util.Properties;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class DefaultCommandLinePolicyEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      DefaultCommandLinePolicy defaultCommandLinePolicy0 = new DefaultCommandLinePolicy();
      Properties properties0 = new Properties();
      String[] stringArray0 = new String[9];
      int int0 = defaultCommandLinePolicy0.processSwitch(properties0, 401, stringArray0, "");
      assertEquals(402, int0);
  }

  @Test
  public void test1()  throws Throwable  {
      DefaultCommandLinePolicy defaultCommandLinePolicy0 = new DefaultCommandLinePolicy();
      Properties properties0 = new Properties();
      String[] stringArray0 = new String[1];
      // Undeclared exception!
      try {
        defaultCommandLinePolicy0.processSwitch(properties0, (-11), stringArray0, "7Ulkuy\"Zcn`k+,L\"+8");
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }
}
