/*
 * This file was automatically generated by EvoSuite
 */

package com.lts.pest.tree;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.lts.pest.tree.TreeListenerHelper;
import com.lts.util.TreeNode;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TreeListenerHelperEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      TreeListenerHelper treeListenerHelper0 = new TreeListenerHelper();
      treeListenerHelper0.resumeAllChanged();
  }

  @Test
  public void test1()  throws Throwable  {
      TreeListenerHelper treeListenerHelper0 = new TreeListenerHelper();
      TreeNode treeNode0 = new TreeNode();
      treeListenerHelper0.addListener((Object) null);
      // Undeclared exception!
      try {
        treeListenerHelper0.fireNodeRemoved(treeNode0, treeNode0);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test2()  throws Throwable  {
      TreeListenerHelper treeListenerHelper0 = new TreeListenerHelper();
      treeListenerHelper0.addListener((Object) null);
      // Undeclared exception!
      try {
        treeListenerHelper0.fireNodeChanged((TreeNode) null);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test3()  throws Throwable  {
      TreeListenerHelper treeListenerHelper0 = new TreeListenerHelper();
      TreeNode treeNode0 = new TreeNode();
      treeListenerHelper0.addListener((Object) null);
      // Undeclared exception!
      try {
        treeListenerHelper0.fireNodeAdded(treeNode0, treeNode0);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test4()  throws Throwable  {
      TreeListenerHelper treeListenerHelper0 = new TreeListenerHelper();
      treeListenerHelper0.addListener((Object) null);
      // Undeclared exception!
      try {
        treeListenerHelper0.fire(3, (Object) null, (Object) null);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test5()  throws Throwable  {
      TreeListenerHelper treeListenerHelper0 = new TreeListenerHelper();
      TreeNode treeNode0 = new TreeNode();
      treeListenerHelper0.addListener((Object) null);
      treeListenerHelper0.fire((-47), (Object) treeNode0, (Object) treeNode0, (Object) treeNode0);
      assertEquals(0, treeNode0.getChildCount());
  }
}
