/*
 * This file was automatically generated by EvoSuite
 */

package com.lts.swing.table.dragndrop.example;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.lts.swing.table.dragndrop.example.ExampleModel;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class ExampleModelEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      ExampleModel exampleModel0 = new ExampleModel();
      assertNotNull(exampleModel0);
      
      exampleModel0.insertString(0, "IIaX&'ccgaj]!Y");
      assertEquals(1, exampleModel0.getRowCount());
  }

  @Test
  public void test1()  throws Throwable  {
      ExampleModel exampleModel0 = new ExampleModel();
      assertNotNull(exampleModel0);
      
      exampleModel0.insertString("#!T", 0);
      assertEquals(1, exampleModel0.getRowCount());
  }

  @Test
  public void test2()  throws Throwable  {
      ExampleModel exampleModel0 = new ExampleModel();
      assertNotNull(exampleModel0);
      
      exampleModel0.addString("");
      assertEquals(1, exampleModel0.getRowCount());
  }

  @Test
  public void test3()  throws Throwable  {
      ExampleModel exampleModel0 = new ExampleModel();
      // Undeclared exception!
      try {
        exampleModel0.setValueAt((Object) null, (-2022), (-62));
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test4()  throws Throwable  {
      ExampleModel exampleModel0 = new ExampleModel();
      // Undeclared exception!
      try {
        exampleModel0.removeRow((-1));
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      } catch(ArrayIndexOutOfBoundsException e) {
        /*
         * -1
         */
      }
  }

  @Test
  public void test5()  throws Throwable  {
      ExampleModel exampleModel0 = new ExampleModel();
      // Undeclared exception!
      try {
        exampleModel0.getString(112);
        fail("Expecting exception: IndexOutOfBoundsException");
      } catch(IndexOutOfBoundsException e) {
        /*
         * Index: 112, Size: 0
         */
      }
  }

  @Test
  public void test6()  throws Throwable  {
      ExampleModel exampleModel0 = new ExampleModel();
      int int0 = exampleModel0.getRowCount();
      assertEquals(0, int0);
  }

  @Test
  public void test7()  throws Throwable  {
      ExampleModel exampleModel0 = new ExampleModel();
      // Undeclared exception!
      try {
        exampleModel0.getValueAt(0, (-245));
        fail("Expecting exception: IndexOutOfBoundsException");
      } catch(IndexOutOfBoundsException e) {
        /*
         * Index: 0, Size: 0
         */
      }
  }
}
