/*
 * This file was automatically generated by EvoSuite
 */

package com.lts.pest.data;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.lts.pest.data.GatherMetaDataEvent;
import com.lts.pest.data.GatherMetaDataListenerHelper;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class GatherMetaDataListenerHelperEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      GatherMetaDataListenerHelper gatherMetaDataListenerHelper0 = new GatherMetaDataListenerHelper();
      gatherMetaDataListenerHelper0.fireStopGathering();
  }

  @Test
  public void test1()  throws Throwable  {
      GatherMetaDataListenerHelper gatherMetaDataListenerHelper0 = new GatherMetaDataListenerHelper();
      gatherMetaDataListenerHelper0.firePeriodChanged((-1069L));
  }

  @Test
  public void test2()  throws Throwable  {
      GatherMetaDataListenerHelper gatherMetaDataListenerHelper0 = new GatherMetaDataListenerHelper();
      GatherMetaDataEvent gatherMetaDataEvent0 = new GatherMetaDataEvent();
      // Undeclared exception!
      try {
        gatherMetaDataListenerHelper0.notifyListener((Object) gatherMetaDataEvent0, 1940, (Object) "[]");
        fail("Expecting exception: ClassCastException");
      } catch(ClassCastException e) {
        /*
         * java.lang.String cannot be cast to com.lts.pest.data.GatherMetaDataEvent
         */
      }
  }

  @Test
  public void test3()  throws Throwable  {
      GatherMetaDataListenerHelper gatherMetaDataListenerHelper0 = new GatherMetaDataListenerHelper();
      gatherMetaDataListenerHelper0.fireStartGathering((-2018L));
  }
}
