/*
 * This file was automatically generated by EvoSuite
 */

package com.lts.pest.data;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.lts.pest.data.GatherMetaDataEvent;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class GatherMetaDataEventEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      GatherMetaDataEvent.EventTypes gatherMetaDataEvent_EventTypes0 = GatherMetaDataEvent.EventTypes.StartGathering;
      GatherMetaDataEvent gatherMetaDataEvent0 = new GatherMetaDataEvent(gatherMetaDataEvent_EventTypes0, (long) 1402104267);
      gatherMetaDataEvent0.getEventType();
      assertEquals(1402104267L, gatherMetaDataEvent0.getPeriod());
  }

  @Test
  public void test1()  throws Throwable  {
      GatherMetaDataEvent.EventTypes gatherMetaDataEvent_EventTypes0 = GatherMetaDataEvent.EventTypes.StartGathering;
      GatherMetaDataEvent gatherMetaDataEvent0 = new GatherMetaDataEvent(gatherMetaDataEvent_EventTypes0, (long) 1402104267);
      gatherMetaDataEvent0.setPeriod((-1L));
      assertEquals((-1L), gatherMetaDataEvent0.getPeriod());
  }

  @Test
  public void test2()  throws Throwable  {
      GatherMetaDataEvent.EventTypes gatherMetaDataEvent_EventTypes0 = GatherMetaDataEvent.EventTypes.StartGathering;
      GatherMetaDataEvent gatherMetaDataEvent0 = new GatherMetaDataEvent(gatherMetaDataEvent_EventTypes0, (long) 1402104267);
      long long0 = gatherMetaDataEvent0.getPeriod();
      assertEquals(1402104267L, long0);
  }

  @Test
  public void test3()  throws Throwable  {
      GatherMetaDataEvent.EventTypes gatherMetaDataEvent_EventTypes0 = GatherMetaDataEvent.EventTypes.StartGathering;
      GatherMetaDataEvent gatherMetaDataEvent0 = new GatherMetaDataEvent(gatherMetaDataEvent_EventTypes0);
      assertEquals(GatherMetaDataEvent.EventTypes.StartGathering, gatherMetaDataEvent0.getEventType());
  }

  @Test
  public void test4()  throws Throwable  {
      GatherMetaDataEvent gatherMetaDataEvent0 = new GatherMetaDataEvent();
      assertEquals(0L, gatherMetaDataEvent0.getPeriod());
  }

  @Test
  public void test5()  throws Throwable  {
      GatherMetaDataEvent.EventTypes gatherMetaDataEvent_EventTypes0 = GatherMetaDataEvent.EventTypes.StartGathering;
      GatherMetaDataEvent gatherMetaDataEvent0 = new GatherMetaDataEvent(gatherMetaDataEvent_EventTypes0, (long) 1402104267);
      gatherMetaDataEvent0.setEventType(gatherMetaDataEvent_EventTypes0);
      assertEquals(1402104267L, gatherMetaDataEvent0.getPeriod());
  }
}
