/*
 * This file was automatically generated by EvoSuite
 */

package com.lts.caloriecount.ui.entry;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.lts.LTSException;
import com.lts.caloriecount.data.Adjustment;
import com.lts.caloriecount.ui.entry.AdjustmentWindow;
import java.awt.HeadlessException;
import java.awt.Window;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class AdjustmentWindowEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      // Undeclared exception!
      try {
        AdjustmentWindow.createAjustment();
        fail("Expecting exception: HeadlessException");
      } catch(HeadlessException e) {
      }
  }

  @Test
  public void test1()  throws Throwable  {
      AdjustmentWindow adjustmentWindow0 = null;
      try {
        adjustmentWindow0 = new AdjustmentWindow((Window) null);
        fail("Expecting exception: IllegalArgumentException");
      } catch(IllegalArgumentException e) {
      }
  }

  @Test
  public void test2()  throws Throwable  {
      Adjustment adjustment0 = new Adjustment();
      // Undeclared exception!
      try {
        AdjustmentWindow.editAdjustment(adjustment0);
        fail("Expecting exception: HeadlessException");
      } catch(HeadlessException e) {
      }
  }

  @Test
  public void test3()  throws Throwable  {
      Adjustment adjustment0 = new Adjustment();
      // Undeclared exception!
      try {
        AdjustmentWindow.edit(adjustment0, 984);
        fail("Expecting exception: HeadlessException");
      } catch(HeadlessException e) {
      }
  }
}
