/*
 * This file was automatically generated by EvoSuite
 */

package com.lts.swing.table.dragndrop;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.lts.swing.table.dragndrop.NewTransferHandler;
import com.lts.swing.table.dragndrop.SimplifiedTransferHandler;
import com.lts.swing.table.dragndrop.SimplifiedTransferHandlerAdaptor;
import java.awt.Component;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.StringSelection;
import java.awt.datatransfer.Transferable;
import javax.swing.JComponent;
import javax.swing.JInternalFrame;
import javax.swing.TransferHandler;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class NewTransferHandlerEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      SimplifiedTransferHandlerAdaptor simplifiedTransferHandlerAdaptor0 = new SimplifiedTransferHandlerAdaptor();
      NewTransferHandler newTransferHandler0 = new NewTransferHandler((SimplifiedTransferHandler) simplifiedTransferHandlerAdaptor0);
      Clipboard clipboard0 = new Clipboard("");
      newTransferHandler0.exportToClipboard((JComponent) null, clipboard0, (int) (byte)2);
  }

  @Test
  public void test1()  throws Throwable  {
      SimplifiedTransferHandlerAdaptor simplifiedTransferHandlerAdaptor0 = new SimplifiedTransferHandlerAdaptor();
      NewTransferHandler newTransferHandler0 = new NewTransferHandler((SimplifiedTransferHandler) simplifiedTransferHandlerAdaptor0);
      JInternalFrame jInternalFrame0 = new JInternalFrame("Fd-J3R[", false);
      StringSelection stringSelection0 = new StringSelection("Fd-J3R[");
      TransferHandler.TransferSupport transferHandler_TransferSupport0 = new TransferHandler.TransferSupport((Component) jInternalFrame0, (Transferable) stringSelection0);
      // Undeclared exception!
      try {
        newTransferHandler0.canImport(transferHandler_TransferSupport0);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test2()  throws Throwable  {
      SimplifiedTransferHandlerAdaptor simplifiedTransferHandlerAdaptor0 = new SimplifiedTransferHandlerAdaptor();
      NewTransferHandler newTransferHandler0 = new NewTransferHandler((SimplifiedTransferHandler) simplifiedTransferHandlerAdaptor0);
      // Undeclared exception!
      try {
        newTransferHandler0.importData((TransferHandler.TransferSupport) null);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test3()  throws Throwable  {
      NewTransferHandler.initializeClass();
  }

  @Test
  public void test4()  throws Throwable  {
      NewTransferHandler newTransferHandler0 = new NewTransferHandler((SimplifiedTransferHandler) null);
      Clipboard clipboard0 = new Clipboard("H=krUpJ");
      newTransferHandler0.exportToClipboard((JComponent) null, clipboard0, (-1));
      assertEquals("H=krUpJ", clipboard0.getName());
  }
}
