/*
 * This file was automatically generated by EvoSuite
 */

package com.lts.caloriecount.ui.mainframe;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.lts.LTSException;
import com.lts.caloriecount.ui.mainframe.HelpAboutPanel;
import java.awt.Dimension;
import java.awt.HeadlessException;
import java.awt.Window;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class HelpAboutPanelEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      HelpAboutPanel helpAboutPanel0 = new HelpAboutPanel();
      String string0 = helpAboutPanel0.getViewName();
      assertEquals("About", string0);
  }

  @Test
  public void test1()  throws Throwable  {
      HelpAboutPanel helpAboutPanel0 = new HelpAboutPanel();
      Dimension dimension0 = helpAboutPanel0.getWindowSize();
      assertEquals("java.awt.Dimension[width=400,height=334]", dimension0.toString());
  }

  @Test
  public void test2()  throws Throwable  {
      HelpAboutPanel helpAboutPanel0 = null;
      try {
        helpAboutPanel0 = new HelpAboutPanel((Window) null);
        fail("Expecting exception: IllegalArgumentException");
      } catch(IllegalArgumentException e) {
      }
  }

  @Test
  public void test3()  throws Throwable  {
      // Undeclared exception!
      try {
        HelpAboutPanel.showDialog();
        fail("Expecting exception: HeadlessException");
      } catch(HeadlessException e) {
      }
  }

  @Test
  public void test4()  throws Throwable  {
      // Undeclared exception!
      try {
        HelpAboutPanel.showAboutWindow();
        fail("Expecting exception: HeadlessException");
      } catch(HeadlessException e) {
      }
  }
}
