/*
 * This file was automatically generated by EvoSuite
 */

package de.outstare.fortbattleplayer.gui;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import de.outstare.fortbattleplayer.gui.GuiPlayer;
import de.outstare.fortbattleplayer.model.Battlefield;
import de.outstare.fortbattleplayer.model.Combatant;
import de.outstare.fortbattleplayer.model.CombatantSide;
import de.outstare.fortbattleplayer.model.Fortbattle;
import de.outstare.fortbattleplayer.player.Battleplan;
import de.outstare.fortbattleplayer.statistics.AllStatistics;
import java.awt.Image;
import java.util.HashMap;
import java.util.Map;
import java.util.Set;

@RunWith(EvoSuiteRunner.class)
public class GuiPlayerEvoSuiteTest {


  //Test case number: 0
  /*
   * 1 covered goal:
   * 1 de.outstare.fortbattleplayer.gui.GuiPlayer.<init>(Lde/outstare/fortbattleplayer/model/Fortbattle;Ljava/lang/String;)V: root-Branch
   */
  @Test
  public void test0()  throws Throwable  {
      HashMap<CombatantSide, Set<Combatant>> hashMap0 = new HashMap<CombatantSide, Set<Combatant>>();
      Fortbattle fortbattle0 = new Fortbattle("", (Map<CombatantSide, Set<Combatant>>) hashMap0, (Battlefield) null, (Battleplan) null, (AllStatistics) null, (Image) null);
      GuiPlayer guiPlayer0 = null;
      try {
        guiPlayer0 = new GuiPlayer(fortbattle0, "");
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }
}
