/*
 * This file was automatically generated by EvoSuite
 */

package com.lts.caloriecount.ui.propertywindow;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.lts.LTSException;
import com.lts.caloriecount.ui.propertywindow.PropertyWindow;
import java.awt.Container;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class PropertyWindowEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      JOptionPane jOptionPane0 = new JOptionPane();
      PropertyWindow propertyWindow0 = null;
      try {
        propertyWindow0 = new PropertyWindow((Container) jOptionPane0);
        fail("Expecting exception: IllegalArgumentException");
      } catch(IllegalArgumentException e) {
      }
  }

  @Test
  public void test1()  throws Throwable  {
      // Undeclared exception!
      try {
        PropertyWindow.createWindow();
        fail("Expecting exception: HeadlessException");
      } catch(HeadlessException e) {
      }
  }
}
