/*
 * This file was automatically generated by EvoSuite
 */

package com.lts.caloriecount.ui.propertywindow;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.lts.caloriecount.data.budget.TimeOfDay;
import com.lts.caloriecount.ui.propertywindow.PropertyListAdaptor;
import com.lts.xml.simple.SimpleElement;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class PropertyListAdaptorEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      PropertyListAdaptor propertyListAdaptor0 = new PropertyListAdaptor();
      SimpleElement simpleElement0 = new SimpleElement();
      propertyListAdaptor0.deserializeFrom(simpleElement0);
  }

  @Test
  public void test1()  throws Throwable  {
      PropertyListAdaptor propertyListAdaptor0 = new PropertyListAdaptor();
      TimeOfDay timeOfDay0 = new TimeOfDay((-1), (-1));
      SimpleElement simpleElement0 = timeOfDay0.createSerializationElement();
      propertyListAdaptor0.serializeTo(simpleElement0);
  }

  @Test
  public void test2()  throws Throwable  {
      PropertyListAdaptor propertyListAdaptor0 = new PropertyListAdaptor();
      propertyListAdaptor0.createSerializationElement();
  }
}
