/*
 * This file was automatically generated by EvoSuite
 */

package com.lts.swing.display;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.lts.LTSException;
import com.lts.Suspender;
import com.lts.event.Callback;
import com.lts.swing.display.ErrorContentPanel;
import java.awt.Container;
import java.awt.HeadlessException;
import java.awt.Window;
import javax.swing.JPasswordField;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class ErrorContentPanelEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      Suspender suspender0 = new Suspender();
      ErrorContentPanel.CloseListener errorContentPanel_CloseListener0 = null;
      try {
        errorContentPanel_CloseListener0 = new ErrorContentPanel.CloseListener((Window) null, (Callback) suspender0);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test1()  throws Throwable  {
      ErrorContentPanel errorContentPanel0 = new ErrorContentPanel("2", (Throwable) null);
      // Undeclared exception!
      try {
        errorContentPanel0.getWindowSize();
        fail("Expecting exception: HeadlessException");
      } catch(HeadlessException e) {
      }
  }

  @Test
  public void test2()  throws Throwable  {
      // Undeclared exception!
      try {
        ErrorContentPanel.showException((Throwable) null);
        fail("Expecting exception: HeadlessException");
      } catch(HeadlessException e) {
      }
  }

  @Test
  public void test3()  throws Throwable  {
      ErrorContentPanel errorContentPanel0 = new ErrorContentPanel(":", (Throwable) null);
      // Undeclared exception!
      try {
        errorContentPanel0.showDetails();
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test4()  throws Throwable  {
      ErrorContentPanel errorContentPanel0 = new ErrorContentPanel("", (Throwable) null);
      JPasswordField jPasswordField0 = new JPasswordField();
      // Undeclared exception!
      try {
        errorContentPanel0.initialize((Container) jPasswordField0);
        fail("Expecting exception: IllegalArgumentException");
      } catch(IllegalArgumentException e) {
      }
  }

  @Test
  public void test5()  throws Throwable  {
      Suspender suspender0 = new Suspender();
      ErrorContentPanel.ActionThread errorContentPanel_ActionThread0 = new ErrorContentPanel.ActionThread((Window) null, (Callback) suspender0);
      // Undeclared exception!
      try {
        errorContentPanel_ActionThread0.run();
        fail("Expecting exception: IllegalMonitorStateException");
      } catch(IllegalMonitorStateException e) {
      }
  }

  @Test
  public void test6()  throws Throwable  {
      Suspender suspender0 = new Suspender();
      ErrorContentPanel.ActionThread.startWaiting((Window) null, (Callback) suspender0);
  }
}
