/*
 * This file was automatically generated by EvoSuite
 */

package com.lts.swing;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.lts.swing.LTSPanel;
import java.awt.Component;
import java.awt.Container;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.util.Vector;
import javax.swing.Action;
import javax.swing.Box;
import javax.swing.DefaultListCellRenderer;
import javax.swing.JComponent;
import javax.swing.JList;
import javax.swing.JMenu;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.JRadioButtonMenuItem;
import javax.swing.JToggleButton;
import javax.swing.JToolTip;
import javax.swing.JTree;
import javax.swing.border.SoftBevelBorder;
import javax.swing.plaf.InsetsUIResource;
import javax.swing.text.DefaultEditorKit;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class LTSPanelEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      LTSPanel lTSPanel0 = new LTSPanel();
      Box box0 = Box.createVerticalBox();
      lTSPanel0.addSimple((JComponent) box0);
      assertEquals(1, lTSPanel0.countComponents());
      assertEquals(1, lTSPanel0.getGridx());
  }

  @Test
  public void test1()  throws Throwable  {
      LTSPanel lTSPanel0 = new LTSPanel();
      lTSPanel0.nextRow();
      assertEquals(1, lTSPanel0.getGridy());
  }

  @Test
  public void test2()  throws Throwable  {
      LTSPanel lTSPanel0 = new LTSPanel();
      DefaultListCellRenderer defaultListCellRenderer0 = new DefaultListCellRenderer();
      lTSPanel0.alignCenter((JComponent) defaultListCellRenderer0);
      assertEquals(0, lTSPanel0.getGridy());
      assertEquals(0, lTSPanel0.getGridx());
  }

  @Test
  public void test3()  throws Throwable  {
      LTSPanel lTSPanel0 = new LTSPanel();
      JToolTip jToolTip0 = new JToolTip();
      lTSPanel0.addVertical((JComponent) jToolTip0);
      assertEquals(1, lTSPanel0.getComponentCount());
      assertEquals(0, lTSPanel0.getGridy());
  }

  @Test
  public void test4()  throws Throwable  {
      LTSPanel lTSPanel0 = new LTSPanel();
      Vector<String> vector0 = new Vector<String>();
      JList jList0 = new JList(vector0);
      lTSPanel0.addFill((JComponent) jList0);
      assertEquals(1, lTSPanel0.countComponents());
      assertEquals(1, lTSPanel0.getGridx());
  }

  @Test
  public void test5()  throws Throwable  {
      LTSPanel lTSPanel0 = new LTSPanel();
      JMenu jMenu0 = new JMenu();
      JPopupMenu jPopupMenu0 = jMenu0.getPopupMenu();
      InsetsUIResource insetsUIResource0 = (InsetsUIResource)jMenu0.getMargin();
      lTSPanel0.addVertical((JComponent) jPopupMenu0, (Insets) insetsUIResource0);
      assertEquals(1, lTSPanel0.getComponentCount());
      assertEquals(1, lTSPanel0.countComponents());
  }

  @Test
  public void test6()  throws Throwable  {
      LTSPanel lTSPanel0 = new LTSPanel();
      Box box0 = Box.createHorizontalBox();
      JToolTip jToolTip0 = box0.createToolTip();
      Vector<GridBagLayout> vector0 = new Vector<GridBagLayout>();
      JList jList0 = new JList(vector0);
      Insets insets0 = jList0.getInsets();
      lTSPanel0.addFill((JComponent) jToolTip0, insets0);
      assertEquals(1, lTSPanel0.getComponentCount());
      assertEquals(1, lTSPanel0.getGridx());
  }

  @Test
  public void test7()  throws Throwable  {
      LTSPanel lTSPanel0 = new LTSPanel();
      // Undeclared exception!
      try {
        lTSPanel0.addSimple((JComponent) lTSPanel0, 1514);
        fail("Expecting exception: IllegalArgumentException");
      } catch(IllegalArgumentException e) {
        /*
         * adding container's parent to itself
         */
      }
  }

  @Test
  public void test8()  throws Throwable  {
      LTSPanel lTSPanel0 = new LTSPanel();
      Box box0 = Box.createVerticalBox();
      lTSPanel0.addButton((JComponent) box0);
      assertEquals(1, lTSPanel0.countComponents());
      assertEquals(1, lTSPanel0.getGridx());
  }

  @Test
  public void test9()  throws Throwable  {
      LTSPanel lTSPanel0 = new LTSPanel();
      // Undeclared exception!
      try {
        lTSPanel0.addHorizontal((JComponent) null);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test10()  throws Throwable  {
      LTSPanel lTSPanel0 = new LTSPanel();
      lTSPanel0.setGridx(100);
      assertEquals(100, lTSPanel0.getGridx());
  }

  @Test
  public void test11()  throws Throwable  {
      LTSPanel lTSPanel0 = new LTSPanel();
      lTSPanel0.setGridy((-1351));
      assertEquals(-1351, lTSPanel0.getGridy());
  }

  @Test
  public void test12()  throws Throwable  {
      LTSPanel lTSPanel0 = new LTSPanel();
      JOptionPane jOptionPane0 = new JOptionPane((Object) "Name");
      SoftBevelBorder softBevelBorder0 = new SoftBevelBorder((-1));
      Insets insets0 = softBevelBorder0.getBorderInsets((Component) jOptionPane0);
      lTSPanel0.addHorizontal((JComponent) jOptionPane0, insets0);
      assertEquals(1, lTSPanel0.countComponents());
      assertEquals(1, lTSPanel0.getGridx());
  }

  @Test
  public void test13()  throws Throwable  {
      LTSPanel lTSPanel0 = new LTSPanel();
      lTSPanel0.setDefaultInsets(127);
      assertEquals(0, lTSPanel0.getGridx());
      assertEquals(0, lTSPanel0.getGridy());
  }

  @Test
  public void test14()  throws Throwable  {
      LTSPanel lTSPanel0 = new LTSPanel();
      // Undeclared exception!
      try {
        lTSPanel0.closeWindow();
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test15()  throws Throwable  {
      LTSPanel lTSPanel0 = new LTSPanel();
      DefaultEditorKit.DefaultKeyTypedAction defaultEditorKit_DefaultKeyTypedAction0 = new DefaultEditorKit.DefaultKeyTypedAction();
      JToggleButton jToggleButton0 = new JToggleButton((Action) defaultEditorKit_DefaultKeyTypedAction0);
      lTSPanel0.alignLeft((JComponent) jToggleButton0);
      assertEquals(0, lTSPanel0.getGridx());
      assertEquals(0, lTSPanel0.getGridy());
  }

  @Test
  public void test16()  throws Throwable  {
      LTSPanel lTSPanel0 = new LTSPanel();
      Box box0 = Box.createVerticalBox();
      lTSPanel0.setFillHorizontal((JComponent) box0);
      assertEquals(0, lTSPanel0.getGridy());
      assertEquals(0, lTSPanel0.getGridx());
  }

  @Test
  public void test17()  throws Throwable  {
      LTSPanel lTSPanel0 = new LTSPanel();
      JRadioButtonMenuItem jRadioButtonMenuItem0 = new JRadioButtonMenuItem();
      lTSPanel0.alignRight((JComponent) jRadioButtonMenuItem0);
      assertEquals(0, lTSPanel0.getGridy());
      assertEquals(0, lTSPanel0.getGridx());
  }

  @Test
  public void test18()  throws Throwable  {
      LTSPanel lTSPanel0 = new LTSPanel();
      lTSPanel0.alignTop((JComponent) lTSPanel0);
      assertEquals(0, lTSPanel0.getGridy());
      assertEquals(0, lTSPanel0.getGridx());
  }

  @Test
  public void test19()  throws Throwable  {
      LTSPanel lTSPanel0 = new LTSPanel();
      LTSPanel lTSPanel1 = new LTSPanel();
      GridBagLayout gridBagLayout0 = new GridBagLayout();
      GridBagConstraints gridBagConstraints0 = gridBagLayout0.getConstraints((Component) lTSPanel1);
      lTSPanel1.addWithConstraint((JComponent) lTSPanel0, gridBagConstraints0);
      assertEquals(1, lTSPanel1.countComponents());
      
      // Undeclared exception!
      try {
        lTSPanel0.openWindow();
        fail("Expecting exception: ClassCastException");
      } catch(ClassCastException e) {
        /*
         * com.lts.swing.LTSPanel cannot be cast to java.awt.Window
         */
      }
  }

  @Test
  public void test20()  throws Throwable  {
      LTSPanel lTSPanel0 = new LTSPanel();
      lTSPanel0.getDialog();
      assertEquals(0, lTSPanel0.getGridy());
      assertEquals(0, lTSPanel0.getGridx());
  }

  @Test
  public void test21()  throws Throwable  {
      LTSPanel lTSPanel0 = new LTSPanel();
      JTree jTree0 = new JTree();
      boolean boolean0 = lTSPanel0.foundDialog((Container) jTree0);
      assertEquals(0, lTSPanel0.getGridy());
      assertEquals(0, lTSPanel0.getGridx());
      assertEquals(true, boolean0);
  }

  @Test
  public void test22()  throws Throwable  {
      LTSPanel lTSPanel0 = new LTSPanel();
      JTree jTree0 = new JTree();
      lTSPanel0.addTitle((JComponent) jTree0);
      boolean boolean0 = lTSPanel0.foundDialog((Container) jTree0);
      assertEquals(1, lTSPanel0.countComponents());
      assertEquals(false, boolean0);
  }
}
