/*
 * This file was automatically generated by EvoSuite
 */

package com.lts.swing;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.lts.swing.SimpleMouseListener;
import java.awt.Component;
import java.awt.event.MouseEvent;
import java.awt.event.MouseWheelEvent;
import javax.swing.Icon;
import javax.swing.JCheckBox;
import javax.swing.JMenu;
import javax.swing.JMenuItem;
import javax.swing.JRadioButton;
import javax.swing.JTextArea;
import javax.swing.JToggleButton;
import javax.swing.MenuElement;
import javax.swing.MenuSelectionManager;
import javax.swing.event.MenuDragMouseEvent;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class SimpleMouseListenerEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      SimpleMouseListener simpleMouseListener0 = new SimpleMouseListener();
      JCheckBox jCheckBox0 = new JCheckBox("$Jz2|_xHz");
      MouseWheelEvent mouseWheelEvent0 = new MouseWheelEvent((Component) jCheckBox0, (-399), (long) (-399), 0, 1596, 1, (-399), false, 1596, 12, (-399));
      simpleMouseListener0.mouseReleased((MouseEvent) mouseWheelEvent0);
      assertEquals(-399, mouseWheelEvent0.getClickCount());
  }

  @Test
  public void test1()  throws Throwable  {
      SimpleMouseListener simpleMouseListener0 = new SimpleMouseListener();
      JRadioButton jRadioButton0 = new JRadioButton();
      MouseWheelEvent mouseWheelEvent0 = new MouseWheelEvent((Component) jRadioButton0, 0, (long) 0, 0, 0, 0, 0, 0, 0, true, 0, 0, 0);
      simpleMouseListener0.mouseReleased((MouseEvent) mouseWheelEvent0);
      assertEquals(false, mouseWheelEvent0.isControlDown());
  }

  @Test
  public void test2()  throws Throwable  {
      SimpleMouseListener simpleMouseListener0 = new SimpleMouseListener();
      simpleMouseListener0.showPopup();
  }

  @Test
  public void test3()  throws Throwable  {
      SimpleMouseListener simpleMouseListener0 = new SimpleMouseListener();
      JToggleButton jToggleButton0 = new JToggleButton((Icon) null);
      MouseWheelEvent mouseWheelEvent0 = new MouseWheelEvent((Component) jToggleButton0, 1788, (long) 1788, (-791), 1788, 148, 0, false, 148, 1788, 0);
      simpleMouseListener0.mousePressed((MouseEvent) mouseWheelEvent0);
      assertEquals(false, mouseWheelEvent0.isMetaDown());
  }

  @Test
  public void test4()  throws Throwable  {
      SimpleMouseListener simpleMouseListener0 = new SimpleMouseListener();
      JTextArea jTextArea0 = new JTextArea("");
      MouseWheelEvent mouseWheelEvent0 = new MouseWheelEvent((Component) jTextArea0, 443, 0L, 443, 0, 0, 443, 1211, 7, true, 0, 7, 0);
      simpleMouseListener0.singleClick((MouseEvent) mouseWheelEvent0);
      assertEquals(false, mouseWheelEvent0.isConsumed());
  }

  @Test
  public void test5()  throws Throwable  {
      SimpleMouseListener simpleMouseListener0 = new SimpleMouseListener();
      // Undeclared exception!
      try {
        simpleMouseListener0.doubleClick((MouseEvent) null);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test6()  throws Throwable  {
      SimpleMouseListener simpleMouseListener0 = new SimpleMouseListener();
      JMenu jMenu0 = new JMenu("Q1ILwCqtG:8", false);
      MenuElement[] menuElementArray0 = new MenuElement[1];
      MenuSelectionManager menuSelectionManager0 = MenuSelectionManager.defaultManager();
      MenuDragMouseEvent menuDragMouseEvent0 = new MenuDragMouseEvent((Component) jMenu0, (-1685), (-1829L), (-1), (-1864), (-1685), 46, 0, 432, false, menuElementArray0, menuSelectionManager0);
      simpleMouseListener0.mouseReleased((MouseEvent) menuDragMouseEvent0);
      assertEquals(-16321, menuDragMouseEvent0.getModifiers());
  }

  @Test
  public void test7()  throws Throwable  {
      SimpleMouseListener simpleMouseListener0 = new SimpleMouseListener();
      JMenuItem jMenuItem0 = new JMenuItem((String) null, 1122);
      MenuElement[] menuElementArray0 = new MenuElement[5];
      MenuSelectionManager menuSelectionManager0 = MenuSelectionManager.defaultManager();
      MenuDragMouseEvent menuDragMouseEvent0 = new MenuDragMouseEvent((Component) jMenuItem0, 1699, (long) 1122, (-509), (-1), 1122, (-1252), 0, 341, false, menuElementArray0, menuSelectionManager0);
      simpleMouseListener0.mousePressed((MouseEvent) menuDragMouseEvent0);
      assertEquals(341, menuDragMouseEvent0.getClickCount());
  }
}
