/*
 * This file was automatically generated by EvoSuite
 */

package com.lts.caloriecount.data.budget;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.lts.application.ApplicationException;
import com.lts.application.data.ApplicationDataElement;
import com.lts.caloriecount.data.budget.Budget;
import com.lts.caloriecount.data.budget.TimeOfDay;
import com.lts.xml.simple.SimpleElement;
import org.evosuite.runtime.System;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class BudgetEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      Budget budget0 = new Budget();
      int int0 = budget0.getDailyAmount();
      assertEquals(0, int0);
  }

  @Test
  public void test1()  throws Throwable  {
      Budget budget0 = new Budget();
      TimeOfDay timeOfDay0 = new TimeOfDay();
      SimpleElement simpleElement0 = timeOfDay0.createSerializationElement();
      budget0.deserializeFrom(simpleElement0);
      assertEquals(1372806007092L, timeOfDay0.toTime());
  }

  @Test
  public void test2()  throws Throwable  {
      Budget budget0 = new Budget();
      String string0 = budget0.getSerializationName();
      assertEquals("budget", string0);
  }

  @Test
  public void test3()  throws Throwable  {
      Budget budget0 = new Budget();
      int int0 = budget0.getBudgetUpToNow();
      assertEquals(0, int0);
  }

  @Test
  public void test4()  throws Throwable  {
      Budget budget0 = new Budget();
      budget0.copyFrom((ApplicationDataElement) budget0);
      assertEquals(0.0, budget0.getCaloriesPerHour(), 0.01D);
  }

  @Test
  public void test5()  throws Throwable  {
      Budget budget0 = new Budget();
      budget0.setCaloriesPerHour((double) 1368L);
      int int0 = budget0.getBudgetUpToNow();
      assertEquals(1368.0, budget0.getCaloriesPerHour(), 0.01D);
      assertEquals(0, int0);
  }

  @Test
  public void test6()  throws Throwable  {
      System.setCurrentTimeMillis(60021L);
      Budget budget0 = new Budget();
      budget0.setCaloriesPerHour((double) 60021L);
      int int0 = budget0.getBudgetUpToNow();
      assertEquals(60021.0, budget0.getCaloriesPerHour(), 0.01D);
      assertEquals(61021, int0);
  }
}
