/*
 * This file was automatically generated by EvoSuite
 */

package com.lts.caloriecount.data;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.lts.caloriecount.data.CalorieCountData;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class CalorieCountDataEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      CalorieCountData calorieCountData0 = new CalorieCountData();
      assertEquals("myData", calorieCountData0.getEntryName());
  }

  @Test
  public void test1()  throws Throwable  {
      CalorieCountData.CalorieCountDataElementsWrapper calorieCountData_CalorieCountDataElementsWrapper0 = new CalorieCountData.CalorieCountDataElementsWrapper();
      // Undeclared exception!
      try {
        calorieCountData_CalorieCountDataElementsWrapper0.valueOf((String) null);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
        /*
         * Name is null
         */
      }
  }
}
