/*
 * This file was automatically generated by EvoSuite
 */

package de.outstare.fortbattleplayer.statistics;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import de.outstare.fortbattleplayer.statistics.RoundStatistics;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class RoundStatisticsEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      RoundStatistics roundStatistics0 = new RoundStatistics("parameters may not be null!", "parameters may not be null!");
      String string0 = roundStatistics0.getDescription();
      assertEquals("parameters may not be null!", string0);
  }

  @Test
  public void test1()  throws Throwable  {
      RoundStatistics roundStatistics0 = new RoundStatistics("parameters may not be null!", "parameters may not be null!");
      String string0 = roundStatistics0.getValueType();
      assertEquals("parameters may not be null!", string0);
  }

  @Test
  public void test2()  throws Throwable  {
      RoundStatistics roundStatistics0 = new RoundStatistics("parameters may not be null!", "parameters may not be null!");
      roundStatistics0.addValue(15.330336445618883);
      double[] doubleArray0 = roundStatistics0.toArray();
      assertNotNull(doubleArray0);
  }

  @Test
  public void test3()  throws Throwable  {
      RoundStatistics roundStatistics0 = null;
      try {
        roundStatistics0 = new RoundStatistics((String) null, (String) null);
        fail("Expecting exception: AssertionError");
      } catch(AssertionError e) {
        /*
         * parameters may not be null!
         */
      }
  }

  @Test
  public void test4()  throws Throwable  {
      RoundStatistics roundStatistics0 = null;
      try {
        roundStatistics0 = new RoundStatistics(" ;uvINm|.9:}^%~<1y", (String) null);
        fail("Expecting exception: AssertionError");
      } catch(AssertionError e) {
        /*
         * parameters may not be null!
         */
      }
  }

  @Test
  public void test5()  throws Throwable  {
      RoundStatistics roundStatistics0 = new RoundStatistics("parameters may not be null!", "parameters may not be null!");
      double[] doubleArray0 = roundStatistics0.toArray();
      assertNotNull(doubleArray0);
  }
}
