/*
 * This file was automatically generated by EvoSuite
 */

package com.lts.xmlser.tags;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.lts.xmlser.XmlSerializer;
import com.lts.xmlser.tags.CollectionTag;
import javax.imageio.metadata.IIOMetadataNode;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class CollectionTagEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      XmlSerializer xmlSerializer0 = new XmlSerializer();
      IIOMetadataNode iIOMetadataNode0 = new IIOMetadataNode();
      String string0 = xmlSerializer0.COLLECTION_TAG.getTagName((Object) iIOMetadataNode0);
      assertEquals("collection", string0);
  }

  @Test
  public void test1()  throws Throwable  {
      CollectionTag collectionTag0 = new CollectionTag();
      assertNotNull(collectionTag0);
  }
}
