/*
 * This file was automatically generated by EvoSuite
 */

package com.lts.xmlser.tags;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.lts.xmlser.XmlSerializer;
import com.lts.xmlser.tags.FloatTag;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class FloatTagEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      FloatTag floatTag0 = XmlSerializer.FLOAT_TAG;
      String string0 = floatTag0.getTagClassName();
      assertNotNull(string0);
      assertEquals("java.lang.Float", string0);
  }

  @Test
  public void test1()  throws Throwable  {
      FloatTag floatTag0 = new FloatTag();
      String string0 = floatTag0.getTagName((Object) "replicate");
      assertEquals("float", string0);
  }

  @Test
  public void test2()  throws Throwable  {
      FloatTag floatTag0 = new FloatTag();
      // Undeclared exception!
      try {
        floatTag0.toValue("r+!!,CB;v}6!");
        fail("Expecting exception: NumberFormatException");
      } catch(NumberFormatException e) {
        /*
         * For input string: \"r+!!,CB;v}6!\"
         */
      }
  }
}
