/*
 * This file was automatically generated by EvoSuite
 */

package com.lts.xmlser.tags;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.lts.xmlser.XmlSerializer;
import com.lts.xmlser.tags.LongTag;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class LongTagEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      LongTag longTag0 = new LongTag();
      String string0 = longTag0.getTagName((Object) "replicate");
      assertEquals("long", string0);
  }

  @Test
  public void test1()  throws Throwable  {
      LongTag longTag0 = new LongTag();
      String string0 = longTag0.getTagClassName();
      assertEquals("java.lang.Short", string0);
  }

  @Test
  public void test2()  throws Throwable  {
      LongTag longTag0 = XmlSerializer.LONG_TAG;
      // Undeclared exception!
      try {
        longTag0.toValue("");
        fail("Expecting exception: NumberFormatException");
      } catch(NumberFormatException e) {
        /*
         * For input string: \"\"
         */
      }
  }
}
