/*
 * This file was automatically generated by EvoSuite
 */

package com.lts.xmlser.tags;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.lts.LTSException;
import com.lts.io.IndentingPrintWriter;
import com.lts.xmlser.XmlSerializer;
import com.lts.xmlser.tags.ReferenceTag;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class ReferenceTagEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      XmlSerializer xmlSerializer0 = new XmlSerializer();
      String string0 = xmlSerializer0.REFERENCE_TAG.getTagName((Object) null);
      assertEquals("reference", string0);
  }

  @Test
  public void test1()  throws Throwable  {
      ReferenceTag referenceTag0 = new ReferenceTag();
      XmlSerializer xmlSerializer0 = new XmlSerializer();
      // Undeclared exception!
      try {
        referenceTag0.write(xmlSerializer0, (IndentingPrintWriter) null, "reference", (Object) "reference", true);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }
}
