/*
 * This file was automatically generated by EvoSuite
 */

package com.lts.xmlser.tags;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.lts.xmlser.tags.ShortTag;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class ShortTagEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      ShortTag shortTag0 = new ShortTag();
      String string0 = shortTag0.getTagName((Object) "");
      assertEquals("short", string0);
  }

  @Test
  public void test1()  throws Throwable  {
      ShortTag shortTag0 = new ShortTag();
      // Undeclared exception!
      try {
        shortTag0.toValue("mH$hj");
        fail("Expecting exception: NumberFormatException");
      } catch(NumberFormatException e) {
        /*
         * For input string: \"mH$hj\"
         */
      }
  }

  @Test
  public void test2()  throws Throwable  {
      ShortTag shortTag0 = new ShortTag();
      String string0 = shortTag0.getTagClassName();
      assertNotNull(string0);
      assertEquals("java.lang.Short", string0);
  }
}
