/*
 * This file was automatically generated by EvoSuite
 */

package com.lts.caloriecount.data.meal;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.lts.caloriecount.data.meal.MealListFoodListListener;
import com.lts.util.notifyinglist.ListEvent;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class MealListFoodListListenerEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      MealListFoodListListener mealListFoodListListener0 = new MealListFoodListListener();
      ListEvent.EventType listEvent_EventType0 = ListEvent.EventType.Delete;
      ListEvent listEvent0 = new ListEvent(listEvent_EventType0);
      mealListFoodListListener0.listEvent(listEvent0);
  }

  @Test
  public void test1()  throws Throwable  {
      MealListFoodListListener mealListFoodListListener0 = new MealListFoodListListener();
      mealListFoodListListener0.allRowsChanged();
  }
}
