/*
 * This file was automatically generated by EvoSuite
 */

package com.lts.swing.panel;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.lts.LTSException;
import com.lts.swing.panel.RootPaneContentPanel;
import com.lts.swing.rootpane.LTSRootPane;
import com.lts.swing.rootpane.RootPaneJInternalFrame;
import java.awt.Component;
import java.awt.Container;
import java.awt.HeadlessException;
import javax.swing.JInternalFrame;
import javax.swing.JRadioButtonMenuItem;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class RootPaneContentPanelEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      RootPaneContentPanel rootPaneContentPanel0 = new RootPaneContentPanel();
      rootPaneContentPanel0.evaluateResultCancel();
      assertEquals(0.5F, rootPaneContentPanel0.getAlignmentX(), 0.01F);
  }

  @Test
  public void test1()  throws Throwable  {
      RootPaneContentPanel rootPaneContentPanel0 = new RootPaneContentPanel();
      // Undeclared exception!
      try {
        rootPaneContentPanel0.displayAndEvaluate();
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test2()  throws Throwable  {
      RootPaneContentPanel rootPaneContentPanel0 = new RootPaneContentPanel();
      rootPaneContentPanel0.evaluateResult();
      assertEquals(false, rootPaneContentPanel0.isFocusTraversalPolicyProvider());
  }

  @Test
  public void test3()  throws Throwable  {
      RootPaneContentPanel rootPaneContentPanel0 = new RootPaneContentPanel();
      // Undeclared exception!
      try {
        rootPaneContentPanel0.showWindow();
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test4()  throws Throwable  {
      RootPaneContentPanel rootPaneContentPanel0 = new RootPaneContentPanel();
      JInternalFrame jInternalFrame0 = new JInternalFrame((String) null, true);
      RootPaneJInternalFrame rootPaneJInternalFrame0 = new RootPaneJInternalFrame(jInternalFrame0);
      rootPaneContentPanel0.setLTSRootPane((LTSRootPane) rootPaneJInternalFrame0);
      rootPaneContentPanel0.setWindowTitle((String) null);
      assertEquals(false, rootPaneContentPanel0.isPreferredSizeSet());
  }

  @Test
  public void test5()  throws Throwable  {
      RootPaneContentPanel rootPaneContentPanel0 = new RootPaneContentPanel();
      rootPaneContentPanel0.noButtonPressed();
      rootPaneContentPanel0.evaluateResult();
      assertEquals(0.5F, rootPaneContentPanel0.getAlignmentY(), 0.01F);
  }

  @Test
  public void test6()  throws Throwable  {
      RootPaneContentPanel rootPaneContentPanel0 = new RootPaneContentPanel();
      // Undeclared exception!
      try {
        rootPaneContentPanel0.reposition((LTSRootPane) null);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test7()  throws Throwable  {
      RootPaneContentPanel rootPaneContentPanel0 = new RootPaneContentPanel();
      rootPaneContentPanel0.evaluateResultYes();
      assertEquals(Component.BaselineResizeBehavior.OTHER, rootPaneContentPanel0.getBaselineResizeBehavior());
  }

  @Test
  public void test8()  throws Throwable  {
      RootPaneContentPanel rootPaneContentPanel0 = new RootPaneContentPanel();
      // Undeclared exception!
      try {
        rootPaneContentPanel0.showAndBlock();
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test9()  throws Throwable  {
      RootPaneContentPanel rootPaneContentPanel0 = new RootPaneContentPanel();
      // Undeclared exception!
      try {
        rootPaneContentPanel0.initializeContainer((Container) rootPaneContentPanel0);
        fail("Expecting exception: HeadlessException");
      } catch(HeadlessException e) {
      }
  }

  @Test
  public void test10()  throws Throwable  {
      JRadioButtonMenuItem jRadioButtonMenuItem0 = new JRadioButtonMenuItem("{8GK] |E/", false);
      RootPaneContentPanel rootPaneContentPanel0 = null;
      try {
        rootPaneContentPanel0 = new RootPaneContentPanel((Container) jRadioButtonMenuItem0);
        fail("Expecting exception: IllegalArgumentException");
      } catch(IllegalArgumentException e) {
      }
  }

  @Test
  public void test11()  throws Throwable  {
      RootPaneContentPanel rootPaneContentPanel0 = new RootPaneContentPanel();
      // Undeclared exception!
      try {
        rootPaneContentPanel0.makeContentFor((LTSRootPane) null);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test12()  throws Throwable  {
      RootPaneContentPanel rootPaneContentPanel0 = new RootPaneContentPanel();
      rootPaneContentPanel0.setWindowTitle("");
      assertEquals("", rootPaneContentPanel0.getWindowTitle());
  }

  @Test
  public void test13()  throws Throwable  {
      RootPaneContentPanel rootPaneContentPanel0 = new RootPaneContentPanel();
      rootPaneContentPanel0.initializeMenuBar();
      assertEquals(true, rootPaneContentPanel0.getVerifyInputWhenFocusTarget());
  }
}
