/*
 * This file was automatically generated by EvoSuite
 */

package de.outstare.fortbattleplayer.gui.battlefield;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import de.outstare.fortbattleplayer.gui.battlefield.MoveTarget;
import de.outstare.fortbattleplayer.model.Combatant;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class CellContentEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      MoveTarget moveTarget0 = new MoveTarget((Combatant) null);
      assertEquals("has to be non empty, but the tooltip of the cell is used", moveTarget0.getToolTipText());
  }
}
