/*
 * This file was automatically generated by EvoSuite
 */

package com.lts.application;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.lts.application.ExcpetionUtil;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class ExcpetionUtilEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      ExcpetionUtil excpetionUtil0 = new ExcpetionUtil();
      assertNotNull(excpetionUtil0);
  }

  @Test
  public void test1()  throws Throwable  {
      String string0 = ExcpetionUtil.objectToString((Object) "null");
      assertEquals("null", string0);
  }

  @Test
  public void test2()  throws Throwable  {
      String string0 = ExcpetionUtil.objectToString((Object) null);
      assertEquals("null", string0);
  }
}
