/*
 * This file was automatically generated by EvoSuite
 */

package com.lts.xml;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.lts.xml.MapElement;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class MapElementEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      MapElement mapElement0 = new MapElement();
  }
}
