/*
 * This file was automatically generated by EvoSuite
 */

package com.lts.swing.table;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.lts.swing.table.TableModelHelper;
import java.util.Vector;
import javax.swing.JTable;
import javax.swing.event.TableModelEvent;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TableModelHelperEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      DefaultTableModel defaultTableModel0 = new DefaultTableModel();
      TableModelHelper tableModelHelper0 = new TableModelHelper((TableModel) defaultTableModel0);
      tableModelHelper0.fireCellChanged((-82), (-82));
  }

  @Test
  public void test1()  throws Throwable  {
      Vector<Integer> vector0 = new Vector<Integer>();
      DefaultTableModel defaultTableModel0 = new DefaultTableModel(vector0, vector0);
      TableModelHelper tableModelHelper0 = new TableModelHelper((TableModel) defaultTableModel0);
      tableModelHelper0.setSource((TableModel) defaultTableModel0);
      assertEquals(0, defaultTableModel0.getRowCount());
  }

  @Test
  public void test2()  throws Throwable  {
      JTable jTable0 = new JTable();
      DefaultTableModel defaultTableModel0 = (DefaultTableModel)jTable0.getModel();
      TableModelHelper tableModelHelper0 = new TableModelHelper((TableModel) defaultTableModel0);
      tableModelHelper0.fireRowRemoved(334);
  }

  @Test
  public void test3()  throws Throwable  {
      JTable jTable0 = new JTable();
      DefaultTableModel defaultTableModel0 = (DefaultTableModel)jTable0.getModel();
      TableModelHelper tableModelHelper0 = new TableModelHelper((TableModel) defaultTableModel0);
      tableModelHelper0.fireTableChanged();
  }

  @Test
  public void test4()  throws Throwable  {
      Vector<TableModelEvent> vector0 = new Vector<TableModelEvent>();
      DefaultTableModel defaultTableModel0 = new DefaultTableModel(vector0, vector0);
      TableModelHelper tableModelHelper0 = new TableModelHelper((TableModel) defaultTableModel0);
      tableModelHelper0.addListener((Object) "cut-to-clipboard");
      // Undeclared exception!
      try {
        tableModelHelper0.fireRowAdded(1265);
        fail("Expecting exception: ClassCastException");
      } catch(ClassCastException e) {
        /*
         * java.lang.String cannot be cast to javax.swing.event.TableModelListener
         */
      }
  }

  @Test
  public void test5()  throws Throwable  {
      DefaultTableModel defaultTableModel0 = new DefaultTableModel();
      TableModelHelper tableModelHelper0 = new TableModelHelper((TableModel) defaultTableModel0);
      tableModelHelper0.fireRowUpdated((-962));
  }
}
