/*
 * This file was automatically generated by EvoSuite
 */

package com.lts.swing.table.rowmodel;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.lts.swing.table.rowmodel.JTableEventHelper;
import com.lts.swing.table.rowmodel.TableEvent;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class JTableEventHelperEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      JTableEventHelper jTableEventHelper0 = new JTableEventHelper();
      TableEvent.Events tableEvent_Events0 = TableEvent.Events.Enter;
      int[] intArray0 = new int[7];
      TableEvent tableEvent0 = new TableEvent(tableEvent_Events0, intArray0);
      jTableEventHelper0.fireEvent(tableEvent0);
  }

  @Test
  public void test1()  throws Throwable  {
      JTableEventHelper jTableEventHelper0 = new JTableEventHelper();
      // Undeclared exception!
      try {
        jTableEventHelper0.notifyListener((Object) "DoubleClick", 369, (Object) "[]");
        fail("Expecting exception: ClassCastException");
      } catch(ClassCastException e) {
        /*
         * java.lang.String cannot be cast to com.lts.swing.table.rowmodel.JTableEventListener
         */
      }
  }
}
