/*
 * This file was automatically generated by EvoSuite
 */

package com.lts.swing.table.rowmodel;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.lts.swing.table.rowmodel.TableEvent;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TableEventEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      TableEvent.Events tableEvent_Events0 = TableEvent.Events.SingleClick;
      TableEvent tableEvent0 = new TableEvent(tableEvent_Events0);
      assertNotNull(tableEvent0);
  }

  @Test
  public void test1()  throws Throwable  {
      TableEvent.Events tableEvent_Events0 = TableEvent.Events.SingleClick;
      TableEvent tableEvent0 = new TableEvent(tableEvent_Events0, 1831516892);
      assertNotNull(tableEvent0);
  }

  @Test
  public void test2()  throws Throwable  {
      TableEvent.Events tableEvent_Events0 = TableEvent.Events.SingleClick;
      int[] intArray0 = new int[2];
      TableEvent tableEvent0 = new TableEvent(tableEvent_Events0, intArray0);
      assertNotNull(tableEvent0);
  }
}
