/*
 * This file was automatically generated by EvoSuite
 */

package com.lts.compare;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.lts.compare.ObjectPrinter;
import java.io.StringWriter;
import java.util.Locale;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class ObjectPrinterEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      Locale locale0 = Locale.CANADA_FRENCH;
      ObjectPrinter.printObject((Object) locale0);
      assertEquals("", locale0.getVariant());
  }

  @Test
  public void test1()  throws Throwable  {
      ObjectPrinter objectPrinter0 = new ObjectPrinter();
      assertNotNull(objectPrinter0);
  }

  @Test
  public void test2()  throws Throwable  {
      StringWriter stringWriter0 = new StringWriter(277);
      ObjectPrinter.printObject((Object) stringWriter0);
      assertEquals("", stringWriter0.toString());
  }
}
