/*
 * This file was automatically generated by EvoSuite
 */

package com.lts.application.international;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.lts.application.ApplicationTerminateException;
import com.lts.application.international.LTSInternationalizationSupport;
import java.util.ResourceBundle;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class LTSInternationalizationSupportEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      LTSInternationalizationSupport lTSInternationalizationSupport0 = new LTSInternationalizationSupport();
      try {
        lTSInternationalizationSupport0.initializeResourceBundles();
        fail("Expecting exception: ApplicationTerminateException");
      } catch(ApplicationTerminateException e) {
        /*
         * Error loading resource bundle(s)
         */
      }
  }

  @Test
  public void test1()  throws Throwable  {
      LTSInternationalizationSupport lTSInternationalizationSupport0 = new LTSInternationalizationSupport();
      String string0 = lTSInternationalizationSupport0.getResourceBundleErrorMessage();
      assertEquals("The system encountered a severe error will cause it to terminate.", string0);
  }

  @Test
  public void test2()  throws Throwable  {
      LTSInternationalizationSupport lTSInternationalizationSupport0 = new LTSInternationalizationSupport();
      ResourceBundle resourceBundle0 = lTSInternationalizationSupport0.getResourceBundle();
      assertNull(resourceBundle0);
  }
}
