/*
 * This file was automatically generated by EvoSuite
 */

package com.lts.swing.rootpane;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.lts.exception.NotImplementedException;
import com.lts.swing.rootpane.RootPaneJApplet;
import java.awt.event.WindowListener;
import javax.swing.JApplet;
import javax.swing.JLayeredPane;
import javax.swing.JMenuBar;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class RootPaneJAppletEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      RootPaneJApplet rootPaneJApplet0 = new RootPaneJApplet((JApplet) null);
      boolean boolean0 = rootPaneJApplet0.supportsWindowListener();
      assertEquals(false, boolean0);
  }

  @Test
  public void test1()  throws Throwable  {
      RootPaneJApplet rootPaneJApplet0 = new RootPaneJApplet((JApplet) null);
      // Undeclared exception!
      try {
        rootPaneJApplet0.getMenuBar();
        fail("Expecting exception: NotImplementedException");
      } catch(NotImplementedException e) {
      }
  }

  @Test
  public void test2()  throws Throwable  {
      RootPaneJApplet rootPaneJApplet0 = new RootPaneJApplet((JApplet) null);
      // Undeclared exception!
      try {
        rootPaneJApplet0.addWindowListener((WindowListener) null);
        fail("Expecting exception: NotImplementedException");
      } catch(NotImplementedException e) {
      }
  }

  @Test
  public void test3()  throws Throwable  {
      RootPaneJApplet rootPaneJApplet0 = new RootPaneJApplet((JApplet) null);
      // Undeclared exception!
      try {
        rootPaneJApplet0.getCloseAction();
        fail("Expecting exception: NotImplementedException");
      } catch(NotImplementedException e) {
      }
  }

  @Test
  public void test4()  throws Throwable  {
      RootPaneJApplet rootPaneJApplet0 = new RootPaneJApplet((JApplet) null);
      // Undeclared exception!
      try {
        rootPaneJApplet0.getContentPane();
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test5()  throws Throwable  {
      RootPaneJApplet rootPaneJApplet0 = new RootPaneJApplet((JApplet) null);
      // Undeclared exception!
      try {
        rootPaneJApplet0.setTitle("m0<l|:B,|@");
        fail("Expecting exception: NotImplementedException");
      } catch(NotImplementedException e) {
      }
  }

  @Test
  public void test6()  throws Throwable  {
      RootPaneJApplet rootPaneJApplet0 = new RootPaneJApplet((JApplet) null);
      // Undeclared exception!
      try {
        rootPaneJApplet0.getTitle();
        fail("Expecting exception: NotImplementedException");
      } catch(NotImplementedException e) {
      }
  }

  @Test
  public void test7()  throws Throwable  {
      RootPaneJApplet rootPaneJApplet0 = new RootPaneJApplet((JApplet) null);
      Integer integer0 = JLayeredPane.PALETTE_LAYER;
      // Undeclared exception!
      try {
        rootPaneJApplet0.setCloseAction(integer0);
        fail("Expecting exception: NotImplementedException");
      } catch(NotImplementedException e) {
      }
  }

  @Test
  public void test8()  throws Throwable  {
      RootPaneJApplet rootPaneJApplet0 = new RootPaneJApplet((JApplet) null);
      // Undeclared exception!
      try {
        rootPaneJApplet0.setMenuBar((JMenuBar) null);
        fail("Expecting exception: NotImplementedException");
      } catch(NotImplementedException e) {
      }
  }

  @Test
  public void test9()  throws Throwable  {
      RootPaneJApplet rootPaneJApplet0 = new RootPaneJApplet((JApplet) null);
      boolean boolean0 = rootPaneJApplet0.supportsAlwaysOnTop();
      assertEquals(false, boolean0);
  }

  @Test
  public void test10()  throws Throwable  {
      RootPaneJApplet rootPaneJApplet0 = new RootPaneJApplet((JApplet) null);
      // Undeclared exception!
      try {
        rootPaneJApplet0.setModal(false);
        fail("Expecting exception: NotImplementedException");
      } catch(NotImplementedException e) {
      }
  }

  @Test
  public void test11()  throws Throwable  {
      RootPaneJApplet rootPaneJApplet0 = new RootPaneJApplet((JApplet) null);
      boolean boolean0 = rootPaneJApplet0.supportsModal();
      assertEquals(false, boolean0);
  }

  @Test
  public void test12()  throws Throwable  {
      RootPaneJApplet rootPaneJApplet0 = new RootPaneJApplet((JApplet) null);
      boolean boolean0 = rootPaneJApplet0.supportsMenuBar();
      assertEquals(false, boolean0);
  }

  @Test
  public void test13()  throws Throwable  {
      RootPaneJApplet rootPaneJApplet0 = new RootPaneJApplet((JApplet) null);
      JApplet jApplet0 = rootPaneJApplet0.getJApplet();
      assertNull(jApplet0);
  }

  @Test
  public void test14()  throws Throwable  {
      RootPaneJApplet rootPaneJApplet0 = new RootPaneJApplet((JApplet) null);
      boolean boolean0 = rootPaneJApplet0.supportsCloseAction();
      assertEquals(false, boolean0);
  }

  @Test
  public void test15()  throws Throwable  {
      RootPaneJApplet rootPaneJApplet0 = new RootPaneJApplet((JApplet) null);
      // Undeclared exception!
      try {
        rootPaneJApplet0.getAlwaysOnTop();
        fail("Expecting exception: NotImplementedException");
      } catch(NotImplementedException e) {
      }
  }

  @Test
  public void test16()  throws Throwable  {
      RootPaneJApplet rootPaneJApplet0 = new RootPaneJApplet((JApplet) null);
      // Undeclared exception!
      try {
        rootPaneJApplet0.removeWindowListener((WindowListener) null);
        fail("Expecting exception: NotImplementedException");
      } catch(NotImplementedException e) {
      }
  }

  @Test
  public void test17()  throws Throwable  {
      RootPaneJApplet rootPaneJApplet0 = new RootPaneJApplet((JApplet) null);
      // Undeclared exception!
      try {
        rootPaneJApplet0.getModal();
        fail("Expecting exception: NotImplementedException");
      } catch(NotImplementedException e) {
      }
  }

  @Test
  public void test18()  throws Throwable  {
      RootPaneJApplet rootPaneJApplet0 = new RootPaneJApplet((JApplet) null);
      // Undeclared exception!
      try {
        rootPaneJApplet0.setAlwaysOnTop(false);
        fail("Expecting exception: NotImplementedException");
      } catch(NotImplementedException e) {
      }
  }

  @Test
  public void test19()  throws Throwable  {
      RootPaneJApplet rootPaneJApplet0 = new RootPaneJApplet((JApplet) null);
      // Undeclared exception!
      try {
        rootPaneJApplet0.close();
        fail("Expecting exception: NotImplementedException");
      } catch(NotImplementedException e) {
      }
  }

  @Test
  public void test20()  throws Throwable  {
      RootPaneJApplet rootPaneJApplet0 = new RootPaneJApplet((JApplet) null);
      boolean boolean0 = rootPaneJApplet0.supportsTitle();
      assertEquals(false, boolean0);
  }
}
