/*
 * This file was automatically generated by EvoSuite
 */

package de.outstare.fortbattleplayer.gui.statistics;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import de.outstare.fortbattleplayer.gui.statistics.StatisticsPanel;
import de.outstare.fortbattleplayer.statistics.AllStatistics;
import de.outstare.fortbattleplayer.statistics.BattleStatistics;
import de.outstare.fortbattleplayer.statistics.CombatantStatistic;
import de.outstare.fortbattleplayer.statistics.RoundStatGenerator;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class StatisticsPanelEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      CombatantStatistic combatantStatistic0 = new CombatantStatistic((-676));
      BattleStatistics battleStatistics0 = new BattleStatistics((-676), (-676));
      RoundStatGenerator roundStatGenerator0 = new RoundStatGenerator();
      AllStatistics allStatistics0 = new AllStatistics(combatantStatistic0, battleStatistics0, roundStatGenerator0);
      StatisticsPanel statisticsPanel0 = new StatisticsPanel(allStatistics0);
      assertEquals(true, statisticsPanel0.isFontSet());
  }
}
