/*
 * This file was automatically generated by EvoSuite
 */

package com.lts.application.swing;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.lts.application.swing.ApplicationBlockingThread;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class ApplicationBlockingThreadEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      ApplicationBlockingThread applicationBlockingThread0 = new ApplicationBlockingThread();
      applicationBlockingThread0.run();
  }
}
