/*
 * This file was automatically generated by EvoSuite
 */

package com.lts.event;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.lts.event.SimpleKeyListenerAdapter;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class SimpleKeyListenerAdapterEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      SimpleKeyListenerAdapter simpleKeyListenerAdapter0 = new SimpleKeyListenerAdapter();
      Object object0 = new Object();
      simpleKeyListenerAdapter0.other(object0, 0);
  }

  @Test
  public void test1()  throws Throwable  {
      SimpleKeyListenerAdapter simpleKeyListenerAdapter0 = new SimpleKeyListenerAdapter();
      simpleKeyListenerAdapter0.insert((Object) null);
  }

  @Test
  public void test2()  throws Throwable  {
      SimpleKeyListenerAdapter simpleKeyListenerAdapter0 = new SimpleKeyListenerAdapter();
      simpleKeyListenerAdapter0.tab((Object) null);
  }

  @Test
  public void test3()  throws Throwable  {
      SimpleKeyListenerAdapter simpleKeyListenerAdapter0 = new SimpleKeyListenerAdapter();
      Object object0 = new Object();
      simpleKeyListenerAdapter0.enter(object0);
  }

  @Test
  public void test4()  throws Throwable  {
      SimpleKeyListenerAdapter simpleKeyListenerAdapter0 = new SimpleKeyListenerAdapter();
      simpleKeyListenerAdapter0.delete((Object) null);
  }
}
