/*
 * This file was automatically generated by EvoSuite
 */

package com.lts.event;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.lts.event.ListenerHelper;
import com.lts.event.WindowClosedHelper;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class WindowClosedHelperEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      WindowClosedHelper windowClosedHelper0 = new WindowClosedHelper();
      windowClosedHelper0.addListener((Object) "focusPainted");
      ListenerHelper.DeferredEvent listenerHelper_DeferredEvent0 = new ListenerHelper.DeferredEvent((-460), (Object) "selectionMode");
      // Undeclared exception!
      try {
        windowClosedHelper0.fire(listenerHelper_DeferredEvent0);
        fail("Expecting exception: ClassCastException");
      } catch(ClassCastException e) {
        /*
         * java.lang.String cannot be cast to com.lts.event.WindowClosedListener
         */
      }
  }
}
